import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/reset.scss';
import '../styles/globals.scss';
import Header from '../components/header/Header';
import Container from '@/components/container/Container';
import { Providers } from '../redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Container>
            <Header />
            
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
